### ISSUE TITLE
Create Auth Route

### ISSUE THREAD

**Issue by ccloops** [shredfellows/services#14]
As a developer, I want to create auth routes so that users can login.

Acceptance Criteria:

- [x] Checkout `dev-branch`
- [x] Set up /login route
- [x] Set up users model
- [x] Implement Canvas OAuth  
- [x] Create a PR to `staging-branch`

Done when, A/C is validated and the wiki has documentation.

**Comment by benbenbuhben** [comment]
Still waiting on AppID and AppSecret env variables.

**Comment by benbenbuhben** [comment]
This is done. We subbed out the Canvas OAuth and replaced with Google. This has been integrated in such a way to pass the profileID back to the routes that need them to fetch/post to the database on their behalf. Still need to with more user accounts.

**Comment by ccloops** [comment]
Nice work!
