### ISSUE TITLE
Create API Routes

### ISSUE THREAD

**Issue by ccloops** [shredfellows/services#15]
As a developer, I want to create API routes and models so that my code is modular and organized.

/api/v1/:model/:id

Acceptance Criteria:

- [x] Check out `dev-branch`
- [x] Create a notes model
- [x] Create a code model
- [x] Create a canvas model(w/ virtual mongoose methods)
- [x] Once completed, create a PR back to `staging-branch`

Done when, A/C is validated and the wiki has documentation.

**Comment by jbach197** [comment]
PR: https://github.com/shredfellows/services/pull/30
