### ISSUE TITLE
Git "All" Route

### ISSUE THREAD

**Issue by johncokos** [shredfellows/services#21]
As a developer, I need a route that will fetch all of the categories and first level topics from our git repository so that I can draw the topic navigation menu

- [x] Route Format: /api/v1/github
- [x] Route Return Format: JSON Object.
  - One Key for each top level category pointing to an object
  - Each topic is a key value pair, with the topic name and a link to our GitHub "GetOne" API Endpoint

```
{

    “string”: {
    “find”: “http://localhost:3000/api/v1/github/string.find”
    “match”: “http://localhost:3000/api/v1/github/string.match”
  },

“array”: {
    “map”: “http://localhost:3000/api/v1/github/array.map”,
    “sort”: “http://localhost:3000/api/v1/github/array.sort”
  }

}
```

**Comment by ccloops** [comment]
Great work!
