### ISSUE TITLE
Git "One" Route

### ISSUE THREAD

**Issue by johncokos** [shredfellows/services#23]
As a developer, I need a route that will fetch the details about one topic from our git repository so that I can draw the topic navigation menu

- [x] Route Format: /api/v1/github/category.topic
- [x] Route Return Format: JSON Object.
  - Use the dotted notation for **category**.**topic** to lead you the repo/**category**/**topic** folder
  - Data to be sourced by reading the repo itself and getting the video link from the config.json file.

```
{
    “name”: “Find”,
    “readme”: “http://github.com/.../category/topic/challenges/README.md”,
    “video”: “http://youtube.com”,
    “challenges”: [
        “http://github.com/.../category/topic/challenges/challenge1.md”,
        “http://github.com/.../category/topic/challenges/challenge2.md”,
    ]
}

```

**Comment by ccloops** [comment]
Looks good to me

 ><(((('>
