### ISSUE TITLE
Refactor the Assignments Data Model

### ISSUE THREAD

**Issue by johncokos** [shredfellows/services#24]
As a developer, I need the assignments data model to support multiple code challenge submissions, identified by the challenge ID.

The assignments data model should contain the following fields:

course_id: String
student_id: Number
assignment_id: Number
notes: String
code: Object

Code will be an object with the following format:

```
code: {
  challenge1: 'code sample',
  challenge2: 'code sample',
}
```

**Comment by ccloops** [comment]
Nice work! 

龴ↀ◡ↀ龴
