### ISSUE TITLE
Front End

### ISSUE THREAD

**Issue by johncokos** [shredfellows/services#28]
As developers, we need a minimalist front-end to wire up all of the endpoints.

This should be a separate server, with simple .html file

- [x] http://localhost:8080

- [x] /index.html
  - Uses $.getJSON() to pull the github "all" route and spit out the JSON to the screen, showing that we have the data we need to draw the menu.

- [x] /topic/category.topic (i.e. /topic/string.match)
- [x] Uses $.getJSON to pull the github "one" route and spit out the JSON to the screen, showing that we have the information we need to run the video, readme, and draw multiple challenges.
- [ ] Uses $.getJSON to pull the assignment route and get any notes or previous code from the user
- [x] Draw a textarea for code editing that shows previous code if we have it
  - This should have a save button that calls the code runner route via ajax
  - It should show the resulting JSON (shows the code output)
- [x] Draw a textarea for note editing that shows previous notes if we have them
  - This should have a save button that calls the assignment PUT route via ajax
  - Show the returned JSON (should be a success/fail message from the route)

**Comment by benbenbuhben** [comment]
This is fully scaffolded out with html placeholders and mock data. Waiting for the backend folks to complete the routes in order to fully integrate. Note: Create new repo called ```web-server-shredfellows``` which is hosting all the relevant files
