### ISSUE TITLE
Create Heroku Account

### ISSUE THREAD

**Issue by johncokos** [shredfellows/services#5]
As a developer I would like a heroku and travis account setup so that I can deploy my code

Acceptance Criteria:

- [ ] Meet with Jeff to create accounts
- [x] Setup Heroku account
- [x] Setup TravisCI to GitHub repo

Done when, A/C is validated and the wiki has documentation.

**Comment by justeban** [comment]
Didn't meet with Jeff but we have an Herkou Server and an Heroku Web Server.

**Comment by ccloops** [comment]
Nice work Justin - thank you
