### ISSUE TITLE
Setup a new repo for mocking the git directory/file structure

### ISSUE THREAD

**Issue by ccloops** [shredfellows/services#7]
As a developer I want to set up a new repository called shredding, so that I can include all functions.

Acceptance Criteria:

- [x] - New repo called `shredding` created
- [x] - Npm init, npm install dependencies
- [x] - Scaffold file tree with structure
- [x]   - Add set up files (.gitignore, .eslintrc.json, .eslintignore)

Done when, A/C is validated and the wiki has documentation.

**Comment by OviParasca** [comment]
- Created the repo with the folders, files, and pushed up to the Shredding repo. (I don't think this repo needs any PR since this is mostly to prove out the Github code)

**Comment by ccloops** [comment]
Nice work
