### ISSUE TITLE
Get subdomain (shred.codefellows.com) pointed at Heroku

### ISSUE THREAD

**Issue by ccloops** [shredfellows/services#9]
As a developer, I want to get a subdomain to point at Heroku so that shredfellows has a Code Fellows address.

Acceptance Criteria:

- [ ] Meet with Jeff to set up subdomain 
- [ ] Set up Heroku to point to subdomain

Done when, A/C is validated and the wiki has documentation.

**Comment by johncokos** [comment]
Will be working on an internal/free account for now.
